#!/usr/bin/env bash
PROGRAMS=~/programs

# Miscelanius
sudo apt install -y \
    # Tmux
    tmux
    # Needed for alacritty
    xclip \
    cmake \
    g++ \
    pkg-config \
    libfreetype6-dev \
    libfontconfig1-dev \
    libxcb-xfixes0-dev \
    libxkbcommon-dev \
    python3

# Rustup
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

# Alacritty
mkdir -p $PROGRAMS/alacritty

pushd $PROGRAMS || exit 1

echo "working directory: $PROGRAMS"

git clone https://github.com/alacritty/alacritty.git
cd alacritty

# Build
cargo build --release

# Terminfo
if ! infocmp alacritty; then
    echo "infocmp alacritty failed, executing tic"
    sudo tic -xe alacritty,alacritty-direct extra/alacritty.info
fi

# Desktop Entry
sudo cp target/release/alacritty /usr/local/bin # or anywhere else in $PATH
sudo cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
sudo desktop-file-install extra/linux/Alacritty.desktop
sudo update-desktop-database

# Shell completions
cat <<EOF >> ~/.bashrc

# Alacritty shell completions for bash
source $(pwd)/extra/completions/alacritty.bash

EOF

popd

